### ISSUE TITLE
Connection problems api.pushbullet.com ?

### ISSUE THREAD

**Issue by Houdje** [Joe-houghton/PushBulletDomoticz#5]
Hi there !
Just installed this stuff and trying to understand whats happening.

I've already had Python installed, so I only installed python-pip and pushbullet.py

My Raspberry Domoticz only has https-access so  I've entered the configuration like:
`DOMOTICZ_ADDRESS = 'https://192.168.16.23:443'
`

Looks like my Pi is not connecting to the Pushbullet-API-service.

All I can see in de logfile is:
`Initialising
Traceback (most recent call last):
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 153, in <modul$
    main()
  File "/home/pi/scripts/PushBulletDomoticz/PBDomoticz.py", line 138, in main
    pb = Pushbullet(API_KEY)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line $
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line $
    self._load_devices()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line $
    resp_dict = self._get_data(self.DEVICES_URL)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line $
    resp = self._session.get(url)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 525,$
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512,$
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622,$
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 513,$
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.pushbullet.c$`

Can you help me out?

Thanks in advance
Maurice Houdijk

**Comment by Joe-houghton** [comment]
Hi,

Have you got the API key from pushbullet and put it in the config section?

Joe

**Comment by Houdje** [comment]
Hi Joe,

Yes, I've created a new account on Pushbullet and have put the API-key in the config section. 

I have even created another API-key because I couldn't check the previous API-key at Pushbullet.

Maurice

**Comment by Joe-houghton** [comment]
From your pi can you try to do a wget to https://API.pushbullet.com and post the response.
This will tell us if there is a general reason why your pi cannot talk to pushbullet or whether there is a problem with the requests library.

Joe

**Comment by Houdje** [comment]
Hi,

On my Domoticz I use another Pushbullet API-connection to push notifications to my smartphone, and that one works fine.

This is the result from wget:
`wget https://api.pushbullet.com`

`--2018-09-01 16:42:18--  https://api.pushbullet.com/`

`Resolving api.pushbullet.com (api.pushbullet.com)... 2a00:1450:4013:c03::79, 74.125.143.121`

`Connecting to api.pushbullet.com (api.pushbullet.com)|2a00:1450:4013:c03::79|:44                       3... connected.`

`HTTP request sent, awaiting response... 200 OK`
`Length: 84 [application/json]`
`Saving to: ‘index.html’`
`index.html          100%[===================>]      84  --.-KB/s    in 0s`
`2018-09-01 16:42:19 (4.71 MB/s) - ‘index.html’ saved [84/84]`

Also the result of Request-system information:
` python -m requests.help`
`{`
 ` "chardet": {`
`    "version": "3.0.4"`
`  },`
`  "cryptography": {`
`    "version": ""`
`  },`
`  "idna": {`
`    "version": "2.7"`
`  },`
`  "implementation": {`
`    "name": "CPython",`
`    "version": "2.7.13"`
`  },`
`  "platform": {`
`    "release": "4.14.62+",`
`    "system": "Linux"`
`  },`
`  "pyOpenSSL": {`
`    "openssl_version": "",`
`    "version": null`
`  },`
`  "requests": {`
`    "version": "2.19.1"`
`  },`
`  "system_ssl": {`
`    "version": "1010006f"`
`  },`
`  "urllib3": {`
`    "version": "1.23"`
`  },`
`  "using_pyopenssl": false`
`}`

`

**Comment by pvklink** [comment]
Hi, i have the same problems.
I've already had Python installed, so I only installed python-pip and pushbullet.py

My Raspberry Domoticz is on another raspberry than de pusbullet service .
Looks like my TFTTT/pushbullet does not connects  to the Raspberry Pushbullet-API-service.

when i start my tfttt device and trigger pushbullet with #command On 181
Nothing happens
On the Raspberry pusbullet  i activated 
python /home/pi/scripts/PushBulletDomoticz/PBDomoticz.py
i says listening for pushes, but no pushes arrive!

I also did 
wget https://api.pushbullet.com
--2018-09-10 23:10:20--  https://api.pushbullet.com/
Herleiden van api.pushbullet.com (api.pushbullet.com)... 108.177.127.121, 2a00:1450:400e:808::2013
Verbinding maken met api.pushbullet.com (api.pushbullet.com)|108.177.127.121|:443... verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 84 [application/json]
Wordt opgeslagen als: ‘index.html.1’

index.html.1        100%[===================>]      84  --.-KB/s    in 0s

2018-09-10 23:10:20 (18,3 MB/s) - '‘index.html.1’' opgeslagen [84/84]
no errors!

Do i have to open ports on my router or forward some ports on my router/firewall ?

**Comment by Joe-houghton** [comment]
Hi both,
No you shouldn't need to open any ports on your router, that's the main reason why I developed this.
I have been working on another solution to this and it has turned out to have faster response times and more reliable. It's been working well for me for the past few months. I thinking I am going to close this repository in favour of the new solution.
From memory i think that I just need to do the documentation to let people know how to install. I will post back when I've managed to update documentation and check code etc

**Comment by kevsterd** [comment]
Hey Joe,

Keep us updated on the other solution and when you upload the new repo.

For what its worth I'm using this and it works.  It takes about two seconds from start to finish to trigger a scene on my Domo.

To get it working:

Made sure Python was working for all users
Setup IFTTT for input from my assistant. ( was testing with Google but shouldnt matter)
Setup Pushbullet with integration into IFTTT - use same Google account
Setup Pushbullet API access.  You need this key for the script.

On the device running this script make sure it has access to Domo, along with a user account.  I have a specific account setup for authenticated API access.   You just need to the get the scene or device I'd to trigger from the script.

Its a little convoluted but it works.  Without inbound ports being open which is really good.

**Comment by Joe-houghton** [comment]
Hi @kevsterd,
Thanks for your input. I think that there must have been an update to the requests library that I'm using. You set up your system a few months ago, so will have an older version which still works.

**Comment by Joe-houghton** [comment]
Just an update - I have managed to create Pypi module for CommandToDomoticz and I have updated the ReadMe for https://github.com/Joe-houghton/IFTTTtoDomoticzUsingPushover explaining how to install and use. However I have not had the time to test that the install process works 100% yet, I will hopefully be able to do this tomorrow evening.

**Comment by pvklink** [comment]
i installed and registrated. All went well!
But after executing the py-file i get an error that domoticz is not defined....

**Comment by Joe-houghton** [comment]
Thanks pvklink, I will test through this tonight.

**Comment by Joe-houghton** [comment]
Hi Guys,
It should be working now. First time using Pypi and I misunderstood their documentation.
@pvklink You should only need to upgrade the CommandToDomoticz module
`pip install CommandToDomoticz -U`
The new version is 0.9.4

**Comment by pvklink** [comment]
Hi, still get same errors:

I did: pip install CommandToDomoticz -U

and:
 
SSIS:~/scripts/IFTTTtoDomoticzUsingPushover $ sudo python3 /home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py
Traceback (most recent call last):
  File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 72, in <module>
    main()
  File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 52, in main
    domoticz = Domoticz(domoticzAddress, domoticzUser, domoticzPassword)
NameError: name 'Domoticz' is not defined

**Comment by Joe-houghton** [comment]
Can you do a 
Pip show CommandToDomoticz
And check the version number is 0.9.4

**Comment by pvklink** [comment]
sudo pip show CommandToDomoticz
Name: CommandToDomoticz
Version: 0.9.4
Summary: Control Domoticz via Commands
Home-page: https://github.com/Joe-houghton/CommandToDomoticz
Author: Joe Houghton
Author-email: github_joe_Houghton@outlook.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests

**Comment by Joe-houghton** [comment]
Ah, i see it is installed into the python 2.7 directory, rather then 3. 
I believe you may need to do pip3 Install CommandToDomoticz 
And use python3 UsingPushover.py

**Comment by pvklink** [comment]
Somebody else an idea?
sudo pip3 Install CommandToDomoticz does not change anything...
commandtodomoticz stays in the 2.7 folder....

perhaps the default active python version must be version 3 instead of versie 2.7 ?

**Comment by Joe-houghton** [comment]
Have you tried
pip3 show CommandToDomoticz

**Comment by pvklink** [comment]
i did
$ sudo update-alternatives --install $HOME/.local/bin/python python /usr/bin/python2 10
$ sudo update-alternatives --install $HOME/.local/bin/python python /usr/bin/python3 10
$ update-alternatives --config python and choosed the 3.4 python version


look like it uses python 3.4 now...
$ sudo update-alternatives --install $HOME/.local/bin/python python /usr/bin/python2 10

Name: CommandToDomoticz
Version: 0.9.3
Summary: Control Domoticz via Commands
Home-page: https://github.com/Joe-houghton/CommandToDomoticz
Author: Joe Houghton
Author-email: github_joe_Houghton@outlook.com
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: requests

**Comment by pvklink** [comment]
Still get:
$ python3 /home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py

Traceback (most recent call last):
  File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 72, in <module>
    main()
  File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 52, in main
    domoticz = Domoticz(domoticzAddress, domoticzUser, domoticzPassword)
NameError: name 'Domoticz' is not defined

**Comment by pvklink** [comment]
Ok, deleted the scripts folder and registration and started all over again!
I have registrated with the pushoverregistration script, and device.cfg is created

But when i startusing pushover.py i still get an error:

$ python3 /home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py

Traceback (most recent call last):
File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 72, in 
main()
File "/home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py", line 52, in main
domoticz = Domoticz(domoticzAddress, domoticzUser, domoticzPassword)
NameError: name 'Domoticz' is not defined

other info:
pi@RPI_GASSIS:~/scripts/IFTTTtoDomoticzUsingPushover $ pip3 show CommandToDomoticz
Name: CommandToDomoticz
Version: 0.9.3
Summary: Control Domoticz via Commands
Home-page: https://github.com/Joe-houghton/CommandToDomoticz
Author: Joe Houghton
Author-email: github_joe_Houghton@outlook.com
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: requests

**Comment by Joe-houghton** [comment]
Somehow you've got version 0.9.3 for python3, which had the issue I mentioned previously. 
You need version 0.9.4
`pip3 uninstall CommandToDomoticz`
then try
`pip3 install CommandToDomoticz --no-cache-dir`

**Comment by pvklink** [comment]
so far so good...

pi@RPI_GASSIS:~/scripts/IFTTTtoDomoticzUsingPushover $  pip3 show CommandToDomoticz
Name: CommandToDomoticz
Version: 0.9.4
Summary: Control Domoticz via Commands
Home-page: https://github.com/Joe-houghton/CommandToDomoticz
Author: Joe Houghton
Author-email: github_joe_Houghton@outlook.com
License: UNKNOWN
Location: /home/pi/.local/lib/python3.5/site-packages
Requires: requests

**Comment by pvklink** [comment]
Ok, where are getting somewhere, the errors are gone !

pi@RPI_GASSIS:~/scripts/IFTTTtoDomoticzUsingPushover $  pip3 show CommandToDomoticz
Name: CommandToDomoticz
Version: 0.9.4
Summary: Control Domoticz via Commands
Home-page: https://github.com/Joe-houghton/CommandToDomoticz
Author: Joe Houghton
Author-email: github_joe_Houghton@outlook.com
License: UNKNOWN
Location: /home/pi/.local/lib/python3.5/site-packages
Requires: requests

The service starts now without error on my rpi3b...

python3 /home/pi/scripts/IFTTTtoDomoticzUsingPushover/UsingPushover.py
Address: http://192.168.20.30:88
Username: admin
Password: xxxxxxxxxxxxxx
Request for Messages sent
pi@RPI_GASSIS:~/scripts/IFTTTtoDomoticzUsingPushover $

and when i went to https://pushover.net/
and fill in 
alle active devices
title test
Message #command On 669

nothing happens on rpi3b 192.168.20.30:88!
No switch 669 on 
I see that pushover.net has delivered message on pushover.net in: Messages Delivered/Pending
I dont see feedback on the started pythonfile UsingPushover.py on the rpi3b with domoticz and usingpushover.pi

andafter some time the started python file is finished and i can see the cursor again, is this normal?

Is there a way to check that 
1) my raspberry pushover service receives data
2) the IFTTTto domoticz receives data
3) some kind of log file, and where can ik find this

**Comment by Joe-houghton** [comment]
Try selecting the device name (probably IFTTTDomoticz), for some reason the "All Active Devices" option from pushbullet doesn't work.

I do not know about the script finishing prematurely. I have been running it for months without issue.

**Comment by pvklink** [comment]
I also select one device "IFTTTDomoticz" and nothing happens
